<?php
define('GOOGLE_MAP_KEY_1','AIzaSyCQXkXmuVgxtvbM6OmMEZV3oexUfCSb35o');
define('GOOGLE_MAP_KEY_2','AIzaSyDyDkz5mawsvUp6YC6pDU9KZuYx15GLOmU');
define('KEY_CALCULATETOTAL','calculateTotal');
define('KEY_PLACEORDER','placeOrder');
define('KEY_CHECKTIME','checkTime');
define('PAYMENT_CASH','cash');
define('PAYMENT_CREDIT','credit');
define('PAYMENT_INSTORE','instore');
define('ID_PAYMENT_SELECTOR','payment-select');
define('LINK_COOKIE_NAME','deliverhopslink');
define('CLASS_MAIN_PAGE','main-page');
define('CLASS_CHANGE_PAGE','change-page');
define('ID_FOOTER','main_footer');
define('ID_ERROR_MESSAGE','error_msg');

define('ID_PAGE_START','start-page');
define('ID_PAGE_CHECKOUT','checkout-page');
define('ID_PAGE_DELIVERY_CONTACT','delivery-contact-page');
define('ID_PAGE_MAIN_MENU','main-menu-page');
define('ID_PAGE_THANKYOU','thankyou-page');

define('ID_CHECKOUT_ADDRESS','address-body');
define('ID_CHECKOUT_CART','cart-checkout');
define('ID_CHECKOUT_TIP_FOOTER','tip-footer');
define('ID_CHECKOUT_CREDIT_CARD_INFO','credit-card-info');
define('ID_BRAINTREE_FORM','bt_form');
define('ID_BRAINTREE_CREDIT_CARD','bt_credit');
define('ID_BRAINTREE_MONTH','bt_month');
define('ID_BRAINTREE_YEAR','bt_year');
define('ID_BRAINTREE_CVV','bt_cvv');
define('ID_BRAINTREE_SUBMIT','brain_tree_btn');
define('ID_GOOGLE_ADDRESS_SEARCH_TEXT','google_address_process');
define('ID_GOOGLE_ADDRESS_SEARCH_BUTTON','google_address_process_button');
define('ID_THANKYOU_CART','thank_you_cart_container');
define('ID_CUSTOMER_NAME','customer_name');
define('ID_CUSTOMER_PHONE','customer_phone');
define('ID_CUSTOMER_EMAIL','customer_email');
define('ID_DELIVERY_STREET_AND_NUMBER','delivery_street_number');
define('ID_DELIVERY_APT','delivery_apt');
define('ID_DELIVERY_CITY','delivery_city');
define('ID_DELIVERY_ZIPCODE','delivery_zipcode');
define('ID_DELIVERY_STATE','delivery_state');
define('ID_SPECIAL_INSTUC','checkout_special_instruc');
define('ID_CONTACT_FORM','main_contact_form');
define('ID_FINAL_ORDERS_ID','disp-number');

define('CLASS_TOGGLE_TODELIVERY','to_delivery');
define('CLASS_TOGGLE_TOPICKUP','to_pickup');
define('CLASS_TOGGLE_ISDELIVERY','only_if_delivery');
define('CLASS_TOGGLE_ISPICKUP','only_if_pickup');
define('CLASS_TOGGLE_ISDELIVERY_ANDCREDIT','only_if_delivery_and_credit');
define('CLASS_TOTALS_SUBTOTAL','totals_subtotal');
define('CLASS_TOTALS_TAX','totals_tax');
define('CLASS_TOTALS_DELIVERY_FEE','totals_delivery_fee');
define('CLASS_TOTALS_TIP','totals_tip');
define('CLASS_TOTALS_GRAND_TOTAL','totals_grand_total');
define('CLASS_CART_PRODUCT_NAME','product_name');
define('CLASS_CART_PRODUCT_QUANTITY','product_quantity');
define('CLASS_CART_PRODUCT_TOTAL','product_total');
define('CLASS_CART_PRODUCT_DESCRIPTION','product_description');
define('CLASS_CART_PRODUCT_ATTRIBUTE','product_attribute');

define('LABEL_PAYMENT_TYPE','chosen_payment');
define('LABEL_CUSTOMER_NAME','customer_name_txt');
define('LABEL_CUSTOMER_PHONE','customer_phone_txt');
define('LABEL_CUSTOMER_EMAIL','customer_email_txt');
define('LABEL_DELIVERY_STREET_AND_NUMBER','delivery_street_number_txt');
define('LABEL_DELIVERY_APT','delivery_apt_txt');
define('LABEL_DELIVERY_CITY','delivery_city_txt');
define('LABEL_DELIVERY_ZIPCODE','delivery_zipcode_txt');
define('LABEL_DELIVERY_STATE','delivery_state_txt');

define('JS_ERROR_NO_BRAINTREE','Error please try again');
define('JS_ERROR_CALC_TOTAL','Error please try again');
define('JS_ERROR_BAD_VALIDATION','Please enter a more specific address');
define('JS_ERROR_NO_ADDRESS_ENTERED','Please enter an address');
define('JS_ERROR_BELOW_MIN','We currently have a $15 min');
define('JS_ERROR_NO_OPEN_MENUS','Online ordering currently not available');
define('JS_ERROR_NO_GOOGLE','An unexpected error has occured please refresh the page and try again');
define('JS_ERROR_BAD_ADDRESS','I could not figure out your address please try again');
define('JS_ERROR_ADDRESS_NOT_OK','I could not figure out your address please try again');
define('JS_ERROR_BAD_JSON_RANGE','An unexpected error has occured please refresh the page and try again');
define('JS_ERROR_CONFIG','ERROR CONFIG');
define('JS_ERROR_ADDRESS_NOT_IN_POLYGON','Your address is not in range for delivery');
define('JS_ERROR_ABOVE_MAX_DISTANCE','Your address is too far away for delivery');
define('JS_ERROR_ABOVE_MAX_DURATION','Your address is too far away for delivery');
define('JS_ERROR_NO_GEOLOCATION','geolocation turned off');
define('JS_ERROR_MORE_THAN_ONE_PLACE','We found multiple locations for your address please enter a more specific address');
?>